-- Таблица пользователей
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- -- Уникальный email
-- ALTER TABLE users ADD CONSTRAINT uc_users_email UNIQUE (email);
--
-- -- Индекс для поиска по email
-- CREATE INDEX idx_users_email ON users(email);