CREATE TABLE profile (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   user_id BIGINT NOT NULL,
   name VARCHAR NOT NULL,
   budget_max BIGINT NOT NULL,
   usage_purpose INTEGER NOT NULL,
   weight_price INTEGER NOT NULL,
   weight_safety INTEGER NOT NULL,
   weight_reliability INTEGER NOT NULL,
   weight_economy INTEGER NOT NULL,
   weight_comfort INTEGER NOT NULL,
   weight_capacity INTEGER NOT NULL,
   weight_dynamics INTEGER NOT NULL,
   weight_appearance INTEGER NOT NULL,
   weight_service_cost INTEGER NOT NULL,
   CONSTRAINT pk_profile PRIMARY KEY (id)
);