-- Таблица профилей
CREATE TABLE IF NOT EXISTS profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    budget_max INTEGER,
    usage_purpose INTEGER NOT NULL DEFAULT 1,
    weight_price INTEGER NOT NULL DEFAULT 5,
    weight_safety INTEGER NOT NULL DEFAULT 5,
    weight_reliability INTEGER NOT NULL DEFAULT 5,
    weight_economy INTEGER NOT NULL DEFAULT 5,
    weight_comfort INTEGER NOT NULL DEFAULT 5,
    weight_capacity INTEGER NOT NULL DEFAULT 5,
    weight_dynamics INTEGER NOT NULL DEFAULT 5,
    weight_appearance INTEGER NOT NULL DEFAULT 5,
    weight_service_cost INTEGER NOT NULL DEFAULT 5,
    weight_features INTEGER NOT NULL DEFAULT 5,
    CONSTRAINT pk_profile PRIMARY KEY (id)
);

-- -- Внешний ключ к users
-- ALTER TABLE profile ADD CONSTRAINT fk_profile_user
--     FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
--
-- -- У пользователя может быть только один профиль
-- ALTER TABLE profile ADD CONSTRAINT uc_profile_user UNIQUE (user_id);
--
-- -- Индекс для поиска по user_id
-- CREATE INDEX idx_profile_user_id ON profile(user_id);