-- Добавить колонку budget_max (если её нет)
ALTER TABLE profile ADD COLUMN IF NOT EXISTS budget_max BIGINT;

-- Добавить колонку usage_purpose (если её нет)
ALTER TABLE profile ADD COLUMN IF NOT EXISTS usage_purpose INTEGER NOT NULL DEFAULT 1;

-- Добавить веса (если их нет)
ALTER TABLE profile ADD COLUMN IF NOT EXISTS weight_price INTEGER NOT NULL DEFAULT 5;
ALTER TABLE profile ADD COLUMN IF NOT EXISTS weight_safety INTEGER NOT NULL DEFAULT 5;
ALTER TABLE profile ADD COLUMN IF NOT EXISTS weight_reliability INTEGER NOT NULL DEFAULT 5;
ALTER TABLE profile ADD COLUMN IF NOT EXISTS weight_economy INTEGER NOT NULL DEFAULT 5;
ALTER TABLE profile ADD COLUMN IF NOT EXISTS weight_comfort INTEGER NOT NULL DEFAULT 5;
ALTER TABLE profile ADD COLUMN IF NOT EXISTS weight_capacity INTEGER NOT NULL DEFAULT 5;
ALTER TABLE profile ADD COLUMN IF NOT EXISTS weight_dynamics INTEGER NOT NULL DEFAULT 5;
ALTER TABLE profile ADD COLUMN IF NOT EXISTS weight_appearance INTEGER NOT NULL DEFAULT 5;
ALTER TABLE profile ADD COLUMN IF NOT EXISTS weight_service_cost INTEGER NOT NULL DEFAULT 5;