ALTER TABLE profile ADD COLUMN IF NOT EXISTS budget_max INTEGER;

ALTER TABLE profile ADD COLUMN IF NOT EXISTS usage_purpose INTEGER NOT NULL DEFAULT 1;

ALTER TABLE profile ADD COLUMN IF NOT EXISTS weight_price INTEGER NOT NULL DEFAULT 5;
ALTER TABLE profile ADD COLUMN IF NOT EXISTS weight_safety INTEGER NOT NULL DEFAULT 5;
ALTER TABLE profile ADD COLUMN IF NOT EXISTS weight_reliability INTEGER NOT NULL DEFAULT 5;
ALTER TABLE profile ADD COLUMN IF NOT EXISTS weight_economy INTEGER NOT NULL DEFAULT 5;
ALTER TABLE profile ADD COLUMN IF NOT EXISTS weight_comfort INTEGER NOT NULL DEFAULT 5;
ALTER TABLE profile ADD COLUMN IF NOT EXISTS weight_capacity INTEGER NOT NULL DEFAULT 5;
ALTER TABLE profile ADD COLUMN IF NOT EXISTS weight_dynamics INTEGER NOT NULL DEFAULT 5;
ALTER TABLE profile ADD COLUMN IF NOT EXISTS weight_appearance INTEGER NOT NULL DEFAULT 5;
ALTER TABLE profile ADD COLUMN IF NOT EXISTS weight_service_cost INTEGER NOT NULL DEFAULT 5;