-- Таблица автомобилей
CREATE TABLE IF NOT EXISTS car_model (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    brand VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,
    generation VARCHAR(255) NOT NULL,
    year_from DATE NOT NULL,
    year_to DATE,
    price BIGINT NOT NULL,
    body_type VARCHAR(100) NOT NULL,
    fuel_type VARCHAR(100) NOT NULL,
    transmission VARCHAR(100) NOT NULL,
    drivetrain VARCHAR(100) NOT NULL,
    power_hp BIGINT NOT NULL,
    safety_rating BIGINT NOT NULL,
    reliability_rating BIGINT NOT NULL,
    economy_rating BIGINT NOT NULL,
    comfort_rating BIGINT NOT NULL,
    capacity_rating BIGINT NOT NULL,
    dynamics_rating BIGINT NOT NULL,
    appearance_rating BIGINT NOT NULL,
    features_rating BIGINT NOT NULL,
    CONSTRAINT pk_car_model PRIMARY KEY (id)
);

-- -- Индексы для быстрого поиска
-- CREATE INDEX idx_car_model_brand ON car_model(brand);
-- CREATE INDEX idx_car_model_price ON car_model(price);
-- CREATE INDEX idx_car_model_body_type ON car_model(body_type);
-- CREATE INDEX idx_car_model_fuel_type ON car_model(fuel_type);