CREATE TABLE car_model
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    brand              VARCHAR(255)                            NOT NULL,
    model              VARCHAR(255)                            NOT NULL,
    generation         VARCHAR(255)                            NOT NULL,
    year_from          date                                    NOT NULL,
    year_to            date                                    NOT NULL,
    price              BIGINT                                  NOT NULL,
    body_type          VARCHAR(255)                            NOT NULL,
    fuel_type          VARCHAR(255)                            NOT NULL,
    transmission       VARCHAR(255)                            NOT NULL,
    drivetrain         VARCHAR(255)                            NOT NULL,
    power_hp           BIGINT                                  NOT NULL,
    safety_rating      BIGINT                                  NOT NULL,
    reliability_rating BIGINT                                  NOT NULL,
    economy_rating     BIGINT                                  NOT NULL,
    comfort_rating     BIGINT                                  NOT NULL,
    capacity_rating    BIGINT                                  NOT NULL,
    dynamics_rating    BIGINT                                  NOT NULL,
    appearance_rating  BIGINT                                  NOT NULL,
    features_rating    BIGINT                                  NOT NULL,
    CONSTRAINT pk_carmodel PRIMARY KEY (id)
);

CREATE TABLE profile
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id             BIGINT,
    name                VARCHAR(255)                            NOT NULL,
    budget_max          INTEGER,
    usage_purpose       INTEGER                                 NOT NULL,
    weight_price        INTEGER                                 NOT NULL,
    weight_safety       INTEGER                                 NOT NULL,
    weight_reliability  INTEGER                                 NOT NULL,
    weight_economy      INTEGER                                 NOT NULL,
    weight_comfort      INTEGER                                 NOT NULL,
    weight_capacity     INTEGER                                 NOT NULL,
    weight_dynamics     INTEGER                                 NOT NULL,
    weight_appearance   INTEGER                                 NOT NULL,
    weight_service_cost INTEGER                                 NOT NULL,
    CONSTRAINT pk_profile PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(255)                            NOT NULL,
    full_name     VARCHAR(255),
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE profile
    ADD CONSTRAINT uc_profile_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE profile
    ADD CONSTRAINT FK_PROFILE_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);